# Generated by Django 5.2.17 on 2026-08-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(unique=True, verbose_name='Competência')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='PLANEJADO', max_length=12, verbose_name='Status')),
                ('justificativa_reabertura', models.TextField(blank=True, verbose_name='Justificativa de reabertura')),
                ('snapshot_json', models.JSONField(blank=True, null=True, verbose_name='Snapshot lógico')),
                ('snapshot_gerado_em', models.DateTimeField(blank=True, null=True, verbose_name='Snapshot gerado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_abertos', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_fechados', to=settings.AUTH_USER_MODEL)),
                ('reaberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_reabertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-competencia'],
            },
        ),
    ]
