# Generated by Django 5.2.17 on 2026-09-09 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('status', models.CharField(choices=[('ASSOCIADA', 'Associada'), ('EX_ASSOCIADA', 'Ex-associada'), ('PROSPECT', 'Prospect')], default='PROSPECT', max_length=12, verbose_name='Status')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor previsto (R$)')),
                ('fase', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Qualificação'), ('REUNIAO_TECNICA', 'Reunião técnica'), ('NEGOCIACAO', 'Negociação'), ('FECHAMENTO', 'Fechamento'), ('RENOVACAO', 'Renovação'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=16, verbose_name='Fase')),
                ('tipo', models.CharField(choices=[('NOVO_CNPJ', 'Novo CNPJ'), ('RENOVACAO', 'Renovação')], default='NOVO_CNPJ', max_length=10, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm_at.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-atualizada_em'],
            },
        ),
    ]
