# Generated by Django 5.2.17 on 2026-08-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('pillars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=10, verbose_name='Status')),
                ('log', models.TextField(blank=True, verbose_name='Log')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to='periods.periodo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação financeira',
                'verbose_name_plural': 'Importações financeiras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('EMBRAPII', 'Embrapii'), ('AT', 'Associação Tecnológica'), ('OUTRAS_FONTES', 'Outras Fontes')], max_length=15, verbose_name='Tipo de recurso')),
                ('valor_captado', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor captado')),
                ('valor_executado', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor executado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='periods.periodo')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='pillars.pilar')),
            ],
            options={
                'verbose_name': 'Financeiro consolidado',
                'verbose_name_plural': 'Financeiro consolidado',
                'ordering': ['periodo', 'pilar__ordem'],
                'unique_together': {('periodo', 'pilar', 'tipo_recurso')},
            },
        ),
    ]
