# Generated by Django 5.2.17 on 2026-09-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiroconsolidado',
            name='tipo_recurso',
            field=models.CharField(choices=[('EMBRAPII', 'Embrapii'), ('AT', 'Associação Tecnológica'), ('AT_LEI_TICS', 'AT – Lei de TICs'), ('OUTRAS_FONTES', 'Outras Fontes')], max_length=15, verbose_name='Tipo de recurso'),
        ),
    ]
