# Generated by Django 5.2.17 on 2026-09-29 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Centro de competência',
                'verbose_name_plural': 'Centros de competência',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.CharField(max_length=20, verbose_name='Período de referência')),
                ('termo_cooperacao', models.CharField(blank=True, max_length=50, verbose_name='Termo de cooperação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='accountability.centrocompetencia', verbose_name='Centro de competência')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['centro__nome', 'periodo_referencia'],
            },
        ),
        migrations.CreateModel(
            name='DespesaAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba', models.CharField(max_length=80, verbose_name='Aba')),
                ('linha', models.PositiveIntegerField(verbose_name='Linha')),
                ('tipo_recurso', models.CharField(max_length=15, verbose_name='Tipo de recurso')),
                ('acao_relacionada', models.CharField(blank=True, max_length=120, verbose_name='Ação relacionada')),
                ('codigo_projeto', models.CharField(blank=True, max_length=60, verbose_name='Código do projeto')),
                ('conta_projeto', models.CharField(blank=True, max_length=60, verbose_name='Conta do projeto')),
                ('marco', models.CharField(blank=True, max_length=120, verbose_name='Marco')),
                ('tipo_despesa', models.CharField(blank=True, max_length=120, verbose_name='Tipo de despesa')),
                ('credor', models.CharField(blank=True, max_length=200, verbose_name='Credor')),
                ('documento', models.CharField(blank=True, max_length=120, verbose_name='Documento')),
                ('numero_nota', models.CharField(blank=True, max_length=60, verbose_name='Número da nota')),
                ('link_documento', models.CharField(blank=True, max_length=500, verbose_name='Link do documento')),
                ('numero_patrimonial', models.CharField(blank=True, max_length=60, verbose_name='Número patrimonial')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('descricao_atividade', models.TextField(blank=True, verbose_name='Descrição da atividade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('fonte_recurso', models.CharField(blank=True, max_length=200, verbose_name='Fonte do recurso')),
                ('data_nota', models.DateField(blank=True, null=True, verbose_name='Data da nota')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('data_movimento', models.DateField(blank=True, null=True, verbose_name='Data do movimento')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor unitário')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_acompanhamento', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Despesa de acompanhamento',
                'verbose_name_plural': 'Despesas de acompanhamento',
                'ordering': ['acompanhamento', 'aba', 'linha'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fonte', models.CharField(choices=[('FINANCEIRO_GERAL', 'FINANCEIRO GERAL'), ('INDICADORES_PE', 'Indicadores Gerais do PE'), ('ACOMPANHAMENTO_V2', 'Acompanhamento Financeiro (v2)')], max_length=20, verbose_name='Tipo de fonte')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=10, verbose_name='Status')),
                ('log', models.TextField(blank=True, verbose_name='Log')),
                ('avisos', models.TextField(blank=True, verbose_name='Avisos')),
                ('resumo', models.JSONField(blank=True, null=True, verbose_name='Resumo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acompanhamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Importação de acompanhamento',
                'verbose_name_plural': 'Importações de acompanhamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='KpiAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, verbose_name='Código')),
                ('sequencia', models.PositiveIntegerField(verbose_name='Sequência')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('meta_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Meta 2024')),
                ('meta_2025', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Meta 2025')),
                ('meta_2026', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Meta 2026')),
                ('meta_2027', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Meta 2027')),
                ('meta_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Meta total')),
                ('executado_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Executado 2024')),
                ('executado_2025', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Executado 2025')),
                ('acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Acumulado')),
                ('gap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Gap')),
                ('projecao_2026', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Projeção 2026')),
                ('projecao_2027', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Projeção 2027')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_acompanhamento', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'KPI de acompanhamento',
                'verbose_name_plural': 'KPIs de acompanhamento',
                'ordering': ['acompanhamento', 'sequencia', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='OverrideAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(choices=[('financeiro', 'Financeiro'), ('fisico', 'Físico')], max_length=12, verbose_name='Base de análise')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('campo', models.CharField(max_length=20, verbose_name='Campo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('chave', models.CharField(max_length=120, verbose_name='Chave')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='accountability.kpiacompanhamento', verbose_name='KPI')),
                ('pilar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides_acompanhamento', to='pillars.pilar', verbose_name='Pilar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Override de acompanhamento',
                'verbose_name_plural': 'Overrides de acompanhamento',
                'ordering': ['acompanhamento', 'chave'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=32, verbose_name='Origem')),
                ('sequencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequência')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(blank=True, max_length=120, verbose_name='Status')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Orçado')),
                ('realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realizado')),
                ('projetado_2026', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Projetado 2026')),
                ('projetado_2027', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Projetado 2027')),
                ('realizado_mais_projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realizado + projetado')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Diferença')),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Percentual')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_financeiros', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Projeto financeiro',
                'verbose_name_plural': 'Projetos financeiros',
                'ordering': ['acompanhamento', 'origem', 'pilar__ordem', 'sequencia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ResumoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=32, verbose_name='Origem')),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('recurso_ou_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Recurso ou meta')),
                ('captado_anos_1_2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Captado anos 1–2')),
                ('captado_ano3_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Captado ano 3 (YTD)')),
                ('captado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Captado')),
                ('realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realizado')),
                ('projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Projetado')),
                ('realizado_mais_projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realizado + projetado')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Diferença')),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Percentual')),
                ('percentual_meta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Percentual da meta')),
                ('percentual_captado', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Percentual captado')),
                ('farol', models.CharField(blank=True, max_length=20, verbose_name='Farol')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos', to='accountability.acompanhamento', verbose_name='Acompanhamento')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_financeiros', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Resumo financeiro',
                'verbose_name_plural': 'Resumos financeiros',
                'ordering': ['acompanhamento', 'origem', 'pilar__ordem', 'ano'],
            },
        ),
        migrations.AddConstraint(
            model_name='acompanhamento',
            constraint=models.UniqueConstraint(fields=('centro', 'periodo_referencia'), name='uniq_centro_periodo_acompanhamento'),
        ),
        migrations.AddConstraint(
            model_name='despesaacompanhamento',
            constraint=models.UniqueConstraint(fields=('acompanhamento', 'aba', 'linha'), name='uniq_despesa_acomp_aba_linha'),
        ),
        migrations.AddConstraint(
            model_name='kpiacompanhamento',
            constraint=models.UniqueConstraint(fields=('acompanhamento', 'codigo'), name='uniq_kpi_acomp_codigo'),
        ),
        migrations.AddConstraint(
            model_name='overrideacompanhamento',
            constraint=models.UniqueConstraint(fields=('acompanhamento', 'chave'), name='uniq_override_acomp_chave'),
        ),
        migrations.AddConstraint(
            model_name='projetofinanceiro',
            constraint=models.UniqueConstraint(fields=('acompanhamento', 'origem', 'nome'), name='uniq_projeto_acomp_origem_nome'),
        ),
        migrations.AddConstraint(
            model_name='resumofinanceiro',
            constraint=models.UniqueConstraint(fields=('acompanhamento', 'origem', 'pilar', 'ano'), name='uniq_resumo_acomp_origem_pilar_ano'),
        ),
    ]
