# Generated by Django 5.2.17 on 2026-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesaacompanhamento',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Valor unitário'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='acumulado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Acumulado'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='executado_2024',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Executado 2024'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='executado_2025',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Executado 2025'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='gap',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Gap'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='meta_2024',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Meta 2024'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='meta_2025',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Meta 2025'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='meta_2026',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Meta 2026'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='meta_2027',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Meta 2027'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='meta_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Meta total'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='projecao_2026',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Projeção 2026'),
        ),
        migrations.AlterField(
            model_name='kpiacompanhamento',
            name='projecao_2027',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Projeção 2027'),
        ),
    ]
