# Generated by Django 5.2.17 on 2026-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_alter_despesaacompanhamento_valor_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocompetencia',
            name='codigo',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Código'),
        ),
    ]
