# Generated by Django 5.2.17 on 2026-10-02 15:39

from django.db import migrations, models


def copiar_sequencias_legadas(apps, schema_editor):
    ProjetoFinanceiro = apps.get_model('accountability', 'ProjetoFinanceiro')
    banco = schema_editor.connection.alias
    projetos = ProjetoFinanceiro.objects.using(banco).exclude(sequencia__isnull=True)
    for projeto in projetos.iterator(chunk_size=500):
        ProjetoFinanceiro.objects.using(banco).filter(pk=projeto.pk).update(
            codigo_projeto_embrapii=str(projeto.sequencia))


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_alter_centrocompetencia_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetofinanceiro',
            name='codigo_projeto_embrapii',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do projeto EMBRAPII'),
        ),
        migrations.RunPython(copiar_sequencias_legadas, migrations.RunPython.noop),
    ]
