# Generated by Django 5.2.17 on 2026-08-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('tipo', models.CharField(choices=[('QTD', 'Quantidade'), ('MON', 'Monetário'), ('PER', 'Percentual'), ('TXT', 'Texto')], default='QTD', max_length=3, verbose_name='Tipo')),
                ('acumulado', models.BooleanField(default=False, verbose_name='Acumulado (YTD)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='pillars.pilar')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['pilar__ordem', 'codigo'],
                'unique_together': {('pilar', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_inicio', models.DateField(verbose_name='Início da vigência')),
                ('competencia_fim', models.DateField(verbose_name='Fim da vigência')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('ACUMULADA', 'Acumulada')], default='MENSAL', max_length=10, verbose_name='Periodicidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor da meta')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='indicators.indicador')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['indicador', '-versao'],
            },
        ),
    ]
