# Generated by Django 5.2.17 on 2026-08-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pilar',
                'verbose_name_plural': 'Pilares',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pilares', to='pillars.pilar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pilares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo usuário–pilar',
                'verbose_name_plural': 'Vínculos usuário–pilar',
                'unique_together': {('usuario', 'pilar')},
            },
        ),
    ]
