# Generated by Django 5.2.17 on 2026-09-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, upload_to='talentos/fotos/', verbose_name='Foto')),
                ('lattes_url', models.URLField(blank=True, verbose_name='Currículo Lattes')),
                ('pilar_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='pillars.pilar', verbose_name='Pilar principal')),
                ('competencias', models.ManyToManyField(blank=True, related_name='colaboradores', to='talentos.competencia', verbose_name='Competências')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_ou_area', models.CharField(max_length=150, verbose_name='Projeto ou área')),
                ('horas_semanais', models.PositiveIntegerField(verbose_name='Horas semanais')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='talentos.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
