# Generated by Django 5.2.17 on 2026-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='vinculo',
            field=models.CharField(choices=[('CLT', 'CLT'), ('BOLSISTA', 'Bolsista'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Vínculo'),
        ),
    ]
