# Generated by Django 5.2.17 on 2026-09-17 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(choices=[(2024, 'Ano 1: 2024'), (2025, 'Ano 2: 2025'), (2026, 'Ano 3: 2026'), (2027, 'Ano 4: 2027')], verbose_name='Ano')),
                ('base', models.CharField(choices=[('financeiro', 'Financeiro'), ('fisico', 'Físico')], max_length=12, verbose_name='Base de análise')),
                ('previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Previsto (projetado PPI / captado AT-Outras)')),
                ('executado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Executado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_anual', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Plano anual',
                'verbose_name_plural': 'Plano anual',
                'ordering': ['ano', 'pilar__ordem', 'base'],
                'constraints': [models.CheckConstraint(condition=models.Q(('previsto__gte', 0)), name='plano_previsto_nao_negativo'), models.CheckConstraint(condition=models.Q(('executado__gte', 0)), name='plano_executado_nao_negativo')],
                'unique_together': {('ano', 'pilar', 'base')},
            },
        ),
    ]
