# Generated by Django 5.2.17 on 2026-08-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('entidade', models.CharField(max_length=100, verbose_name='Entidade')),
                ('registro_id', models.CharField(blank=True, max_length=40, verbose_name='Registro')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor novo')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
