# Generated by Django 5.2.17 on 2026-09-09 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('pillars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestaqueMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('DESTAQUE', 'Destaque'), ('PENDENCIA_EMBRAPII', 'Pendência EMBRAPII'), ('FOCO_30_DIAS', 'Foco 30 dias')], default='DESTAQUE', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='periods.periodo', verbose_name='Período')),
                ('pilar', models.ForeignKey(blank=True, help_text='Vazio = destaque geral do período.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='pillars.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Destaque mensal',
                'verbose_name_plural': 'Destaques mensais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
